[tool.poetry]
name = "restaurantbookinglab-backend"
version = "0.1.0"
description = ""
authors = ["Sergio Vargas <svargas219@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.7"
djangorestframework = "^3.14.0"
drf-yasg = "^1.21.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
