# Generated by Django 4.2.7 on 2023-11-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='page_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
